name: Sync Translation keys with EN

on:
  workflow_dispatch:
    branches:
      - aniketh/test-ga
  push:
    branches:
      - aniketh/test-ga

jobs:
  sync-translation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Run Sync Translation
        working-directory: .github
        env:
          OPENAI_API_KEY: ${{ secrets.OPEN_AI }}
        run: deno run syncWithEn.js --allow-env
